In [21]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [3]:
df=pd.read_csv('sales_data_EDA_final.csv')
df

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,...,Item_Type_Snack Foods,Item_Type_Soft Drinks,Item_Type_Starchy Foods,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.300000,0,0.252232,249.8092,23.0,6.417137,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
1,5.920000,1,0.268136,48.2692,13.0,3.964431,0,0,0,0,...,0,1,0,1,0,0,1,0,1,0
2,17.500000,0,0.255913,141.6180,23.0,5.632405,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
3,13.650000,1,0.233562,57.6588,35.0,3.742265,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0
4,12.857645,0,0.503272,107.7622,37.0,6.525631,0,0,0,0,...,1,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7992,6.865000,0,0.384362,214.5218,35.0,6.002014,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0
7993,8.380000,1,0.360838,108.1570,20.0,4.160967,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0
7994,10.600000,0,0.327686,85.1224,18.0,4.958269,0,0,0,0,...,0,0,0,0,1,1,0,1,0,0
7995,7.210000,1,0.525625,103.1332,13.0,5.472011,0,0,0,0,...,1,0,0,1,0,0,1,0,1,0
7996,14.800000,0,0.355368,75.4670,25.0,4.485320,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0

In [5]:
x=df.drop(['Item_Outlet_Sales'],axis=1)
y=df['Item_Outlet_Sales']

In [8]:
#Splitting the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [10]:
x_train.shape

(6397, 27)

In [26]:
model=KNeighborsRegressor()
model.fit(x_train,y_train)

KNeighborsRegressor()

In [27]:
#evaluate the model
#training_data
print('#'*50)
print('Training Data Evaluation')
print('#'*50)
y_pred=model.predict(x_train)

r2=r2_score(y_train,y_pred)
print('R2 Score==',r2)

mse=mean_squared_error(y_train,y_pred)
print('MSE==',mse)

mae=mean_absolute_error(y_train,y_pred)
print('MAE==',mae)

print('#'*50)
print('Testing Data Evaluation')
print('#'*50)

y_pred=model.predict(x_test)

r2=r2_score(y_test,y_pred)
print('R2 Score==',r2)

mse=mean_squared_error(y_test,y_pred)
print('MSE==',mse)

mae=mean_absolute_error(y_test,y_pred)
print('MAE==',mae)

##################################################
Training Data Evaluation
##################################################
R2 Score== 0.6915712824322477
MSE== 0.3895161957218376
MAE== 0.48690849909766326
##################################################
Testing Data Evaluation
##################################################
R2 Score== 0.5094347575285716
MSE== 0.5933575129613271
MAE== 0.5959561663326423

In [22]:
# Hyperparameter Tuning
model=KNeighborsRegressor()

hyp={'n_neighbors':np.arange(3,30),
     'p':[1,2]}

gscv_model=GridSearchCV(model,hyp,cv=5)
gscv_model.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
                         'p': [1, 2]})

In [23]:
gscv_model.best_estimator_

KNeighborsRegressor(n_neighbors=9, p=1)

In [24]:
model_01=gscv_model.best_estimator_
model_01.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=9, p=1)

In [25]:
#evaluate the model
#training_data
print('#'*50)
print('Training Data Evaluation')
print('#'*50)
y_pred=model_01.predict(x_train)

r2=r2_score(y_train,y_pred)
print('R2 Score==',r2)

mse=mean_squared_error(y_train,y_pred)
print('MSE==',mse)

mae=mean_absolute_error(y_train,y_pred)
print('MAE==',mae)

print('#'*50)
print('Testing Data Evaluation')
print('#'*50)

y_pred=model_01.predict(x_test)

r2=r2_score(y_test,y_pred)
print('R2 Score==',r2)

mse=mean_squared_error(y_test,y_pred)
print('MSE==',mse)

mae=mean_absolute_error(y_test,y_pred)
print('MAE==',mae)

##################################################
Training Data Evaluation
##################################################
R2 Score== 0.7151908700001333
MSE== 0.3596868984809263
MAE== 0.4720242784418443
##################################################
Testing Data Evaluation
##################################################
R2 Score== 0.627006081147025
MSE== 0.45115047883399606
MAE== 0.5253402197419634